### ISSUE TITLE
How to create a LB?

### ISSUE THREAD

**Issue by Linutux** [kalmhq/kalm#131]
I have created a cluster using RKE. Now I want to point a load balancer, provided by my provider, to my kalm instance. I created a LB from 443 to 3010 on each node, but have no success reaching the kalm dashboard. Only the kubectl-localhost-port-forwarding-method works. I can't access it publicly via LB. Am I missing something?

**Comment by infrar** [comment]
hey @Linutux, to move from port-forwarding to a permanent solution, click "FINISH THE SETUP STEPS" on the top navigation bar.

![Screenshot from 2020-09-05 10-20-37](https://user-images.githubusercontent.com/67806321/92310330-1c5e5880-ef62-11ea-80ca-3e4b5efcfc70.png)

Follow steps to setup a domain (if you don't have one it defaults to nip.io which resolves to the ip). When completed you should have a permanent URL to visit Kalm with built-in authentication.

![Screenshot from 2020-09-05 10-24-52](https://user-images.githubusercontent.com/67806321/92310343-43b52580-ef62-11ea-856e-acde5bfb70a7.png)

**Comment by davidqhr** [comment]
Ingress traffic should enter from the service of istio-ingressgateway. You can check whether the service of istio-ingressgateway in istiod-system is created normally. If it has been created, you can find the corresponding nodePort through this command. `kubectl get svc -n istio-system istio-ingressgateway -o yaml`. These nodePorts are the ports that actually receive traffic. Give it a try.

**Comment by infrar** [comment]
I added a section in the installation documentation regarding configuring access beyond port-fowarding: [https://kalm.dev/docs/install#step-4-optional-configure-access](https://kalm.dev/docs/install#step-4-optional-configure-access)

Closing this issue for now.
