### ISSUE TITLE
Unable to see created pods / deploymnets through command line on kalm dashboard

### ISSUE THREAD

**Issue by ammuvisalakshi** [kalmhq/kalm#136]
Unable to see created pods / deploymnets through command line on kalm dashboard.

Could some body please help.

**Comment by infrar** [comment]
Hi @ammuvisalakshi 

Could you give a bit more information? How did you create the pods / deployments? Did you create a new Application through the Kalm UI, or are you referring to pods created before-hand (or through kubectl)?

**Comment by ammuvisalakshi** [comment]
Hello,

Thank you for the reply back.

I did the following ways ,

a) I have manually created the deployment using local docker image using kubectl that had successfully created deployment and pods , however i could not see them on kalm dashboard

b) I also tried creating app using the kalm dashboard, it wasnt successfull as the docker image it was looking for on the remote repository, it would be nice, if there is an option to look up locally like adding additional parameters like --image-pull-policy=Never.
  
for b) , I am able to see the pods when I do kubectl get pods --all-namespaces.

Thanks again, for looking into this, let me  know, if more details are required.

**Comment by davidqhr** [comment]
a) The kalm dashboard only displays resources created through the kalm api. The underlying logic is actually that kalm has its own way of organizing workload, and it is difficult to convert resources created through native api into a format that conforms to kalm. So you can't see the resources created directly through kubectl. (This part may have better support in the future, but I am not sure when it will happen.)

b) It looks like you are using a private registry. Have you tried adding your registry to the page in the registry? Kalm supports to use image in private image registry.

**Comment by ammuvisalakshi** [comment]
Thank you David.

a) thank you for confirming that kalm doesnot support showing pods/deployments created using native kubectl. Hope this is available sooner. Other wise it is harder just to use only kalm UI to deploy apps not native way.

b) Yes trying out linking an private repo and use image from it.
