### ISSUE TITLE
Endless error-out in install script when applying manifests to supported kubernetes API version with unsupported client

### ISSUE THREAD

**Issue by zephinzer** [kalmhq/kalm#142]
This happens when attempting to apply using a supported version of the Kubernetes server but an unsupported Kubernetes client and feels more like a UX issue to me.

Referencing the command from https://kalm.dev/docs/install:

```sh
curl -sL https://get.kalm.dev | bash
```

This results in an endless loop of:

```
Awaiting installation of CRDs
error: SchemaError(io.k8s.api.policy.v1beta1.PodDisruptionBudgetList): invalid object doesn't have additional properties
```

Output of `kubectl version` follows:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

While the approrpriate error is dumped to stdout:

```
error: SchemaError(io.k8s.api.policy.v1beta1.PodDisruptionBudgetList): invalid object doesn't have additional properties
```

This is quickly overridden by the endless `Awaiting installation of CRDs`. I see a commented `sleep 1` which would help with this problem but a better way would be to error out if the `kubectl apply -f ...` exits with a non-zero exit code. Could raise an MR to fix this behaviour if a maintainer could indicate what the project's preference for this behaviour is?

**Comment by davidqhr** [comment]
Thanks for the feedback.  I think there are two things we can do. First, we can update the install script to make it exits when a kubectl command fails without swallowing the errors. Second, update the docs to tell user use fit version kubectl along with their cluster when trying kalm. Merge Request is well welcomed. I will fix the doc later.
