### ISSUE TITLE
Broken setup process

### ISSUE THREAD

**Issue by aemadrid** [kalmhq/kalm#148]
Started the "finish setup" process but it broke and I don't have an user now. I can still get into the admin with port forward but I can't access apps (times out) or single sign-on. It seems that it created the main domain with all its certs (e.g. kalm-cert and sso-domain-*) and I can go to the domain but I can't login. How can I create a user manually?

**Comment by aemadrid** [comment]
I got it to redo the setup but keeps failing on `XHR failed loading: POST "http://localhost:3010/v1alpha1/initialize"`.

**Comment by davidqhr** [comment]
#137

**Comment by aemadrid** [comment]
The problem is that the setup or reconfigure process never finishes successfully. Timeouts keep happening and I never get to see the username/password created.

**Comment by davidqhr** [comment]
Seems you have a few issues that are talking about the same timeout problem. Could you please choose one for continue discussion then close the others?

**Comment by iAladdin** [comment]
closed for now, please check #150
