### ISSUE TITLE
Login page points to missing documentation

### ISSUE THREAD

**Issue by aemadrid** [kalmhq/kalm#149]
When getting a login page with `http://localhost:3020/login` I'm presented with a request for a token.

![Screen Shot 2020-09-16 at 1 04 05 PM](https://user-images.githubusercontent.com/616/93381088-5dd1ec00-f81d-11ea-97ee-99cb9c50af5e.png)

The "View Instructions" link (https://kalm.dev/docs/install#step-4-admin-service-account) has no information on how to get a token.

**Comment by davidqhr** [comment]
Kalm api server will serve on two address
- 0.0.0.0:3001 
- localhost:3010

The first one is for external access, and it  will ask you for a token. The second is admin interface, which has admin permission but can only accept traffic from localhost. Both of the ports can be accessed via port-forward. Which port were you connecting with?  Can you provide the port-forward command you were using?

**Comment by aemadrid** [comment]
I've only run the port forwarding recommendation from the setup script. I've changed the local port to try to make it work because I keep getting timeouts when trying to work with apps of finish the setup process.

**Comment by nikhiljha** [comment]
This is happening to me when kalm segfaults, see #156

**Comment by iAladdin** [comment]
closed for now, please check #150
