### ISSUE TITLE
SSO page gets into bad state if I incorrectly setup a Github connector

### ISSUE THREAD

**Issue by infrar** [kalmhq/kalm#189]
Repro:

1) Install Kalm on GKE, finished the setup steps
2) Login via generated email/password
3) Go to SSO and add a Github corrector
4) type in a non-existing org (I did this by accident)
5) Log out by clearing the cache (because I wanted to test Github SSO login)
6) Log in via generated email/password again
7) visit /sso (so I can edit the SSO settings)

Result:

![Screenshot from 2020-10-02 15-06-57](https://user-images.githubusercontent.com/67806321/94973715-3f2c5000-04c1-11eb-921b-74fde649db71.png)

**Comment by davidqhr** [comment]
Fixed in v0.1.0-rc.2. Please test and close this issue if it is fixed.

**Comment by davidqhr** [comment]
fixed in v0.1.0-rc.12
