### ISSUE TITLE
Project installation issues

### ISSUE THREAD

**Issue by dylanyht** [kalmhq/kalm#232]
Is the project still installable? My execution of the script on your documentation did not do anything

**Comment by swinges** [comment]
Hey @dylanyht  - which script are you following? Can you point me to the specific docs you're referencing?

As a relevant note, we're finishing up a big refactor on the installation process this week

**Comment by mingmin-kalm** [comment]
Hi @dylanyht 

I have updated the installation steps in README.md, please follow the instructions at https://github.com/kalmhq/kalm#installation

let me know if you have any further issues.

**Comment by dylanyht** [comment]
Hi @mingmin-kalm  I see that the README.md has been updated, I'm going to try with the new documentation in the deployment, I'll give feedback if I have any other questions, thanks.

**Comment by mingmin-kalm** [comment]
Feel free to reopen this if you have further issues.
