### ISSUE TITLE
Question about DNS

### ISSUE THREAD

**Issue by FingerLiu** [kalmhq/kalm#248]
In the demo gif in github homepage, I noticed we can access the app I deployed in kalm through `xxx.kapp.live`.
This is a little confusing me, how could I accomplish this since I didn't find any resolve in public DNS server?
Do I need to config my DNS config of my desktop?
PS: I know this this not a bug, but I didn't find a place to ask this question..

**Comment by swinges** [comment]
For the demo video, we had a domain already configured in the Certificates section (kapp.live). If you're following the self installation instructions, a new Kalm instance will not have any certs pre-configured.

To get a route setup for a component to a public site similar to what's shown in the demo, you'll need to add a cert for the domain. It's pretty straightforward, just adding a record to your DNS and Kalm will check it. There's also two docs (partially complete, but should have enough details) that we have on this process that can help https://docs.kalm.dev/https-certs and https://docs.kalm.dev/cert-issuing

Feel free to comment here if you have any issues!

**Comment by FingerLiu** [comment]
>Suppose we submit a certificate request for: *.example.com. After submit this first wildcard certificate request at Kalm dashboard, Kalm will start a DNS server, in order to make the DNS server publicly known. 

I noticed that kalm will start a DNS server, my question is what DNS instance kalm starts, and is it accessible if we deployed kalm in private cloud which can not access outer network?

**Comment by davidqhr** [comment]
The `kapp.live` is an internal test domain, it's not publicly accessible. You can use any domain in a fresh Kalm installation. The built-in DNS server is for SSL certification application purposes(Let's Encrypt), it helps you do the DNS01 challenge.

**Comment by FingerLiu** [comment]
Thanks!
